import { useQuery } from '@tanstack/react-query';
import {
  createAsset,
  deleteAsset,
  bulkUpdateAssetStatus,
  bulkSoftDeleteAssets,
  getAssetRelatedCounts,
} from '@rgr/shared';
import type { AssetStatus, CreateAssetInput } from '@rgr/shared';
import { assetKeys } from './useAssetData';
import { useMutationFromService } from './useMutationFromService';

export function useAssetRelatedCounts(assetId: string | null) {
  return useQuery({
    queryKey: ['admin-asset-counts', assetId],
    queryFn: async () => {
      if (!assetId) throw new Error('No asset ID');
      const result = await getAssetRelatedCounts(assetId);
      if (!result.success) throw new Error(result.error);
      return result.data;
    },
    enabled: !!assetId,
  });
}

export function useCreateAsset() {
  return useMutationFromService({
    // QR code is auto-generated by the trg_asset_qr_code database trigger,
    // so a single createAsset call returns the asset with QR data populated.
    serviceFn: (input: CreateAssetInput) => createAsset(input),
    invalidates: [assetKeys.lists(), assetKeys.countsByStatus()],
  });
}

export function useDeleteAsset() {
  return useMutationFromService({
    serviceFn: (id: string) => deleteAsset(id),
    invalidates: (_data, id) => [
      assetKeys.lists(),
      assetKeys.countsByStatus(),
      assetKeys.detail(id),
    ],
  });
}

export function useBulkUpdateStatus() {
  return useMutationFromService({
    serviceFn: ({ ids, status }: { ids: string[]; status: AssetStatus }) =>
      bulkUpdateAssetStatus(ids, status),
    invalidates: [assetKeys.lists(), assetKeys.countsByStatus()],
  });
}

export function useBulkDeleteAssets() {
  return useMutationFromService({
    serviceFn: (ids: string[]) => bulkSoftDeleteAssets(ids),
    invalidates: [assetKeys.lists(), assetKeys.countsByStatus()],
  });
}
